PR2CD_UI/PR2CD_UI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('UI.urls'))
]

PR2CD_UI/UI/urls.py
from django.urls import path

from . import views

app_name = "UI"

urlpatterns = [
    path('', views.index, name='index'),
    path('submit', views.submit_req, name="submit"),
    path('diagram', views.diagram, name="diagram"),
    path('about', views.about, name="about"),
    path('contact', views.contact, name="contact"),
    path('samples', views.samples, name="samples")
]

PR2CD_UI/UI/models.py
from django.db import models

# Create your models here.

PR2CD_UI/UI/forms.py
# UI/forms.py

from django import forms

from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox


class RequirementForm(forms.Form):
    req = forms.CharField(
        label='متن نیازمندی را وارد کنید',
        required=True,
        widget=forms.Textarea(attrs={
            'id': 'req',
            'class': 'req-input',
            'rows': 12,
        }),
        error_messages={
            'required': 'نیازمندی نمی‌تواند خالی باشد.',  # Custom error message in Farsi
        }
    )
    # requirement_file = forms.FileField(
    #     label='بارگذاری فایل',
    #     required=False,
    #     widget=forms.ClearableFileInput(attrs={
    #         'id': 'requirement-file',
    #         'class': 'd-none',
    #         'accept': '.txt, .pdf, .doc, .docx, text/plain, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    #     })
    # )
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox(api_params={'hl':'fa'}))

PR2CD_UI/UI/views.py
import json
import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from Extractors import HazmExtractor
from Requirement import Requirement
from ClassDiagramExtractor import ClassDiagramExtractor, ExtractorEvaluator
from Diagram import ClassDiagram
from hazm.dependency_parser import SpacyDependencyParser
from hazm import POSTagger, Lemmatizer, DependencyParser, word_tokenize
from .forms import RequirementForm

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
model_path = os.path.join(BASE_DIR, 'pos_tagger.model')
# Path to the model file
spacy_parser_path = os.path.join(BASE_DIR, 'spacy_dependency_parser')
lemmatizer = Lemmatizer()
tagger = POSTagger(model=model_path)
spacy_parser = SpacyDependencyParser(tagger=tagger, lemmatizer=lemmatizer,
                                     model_file=spacy_parser_path,
                                     working_dir=spacy_parser_path)
hazm_extractor = HazmExtractor(spacy_parser, lemmatizer, with_ezafe_tag=True)


def index(request):
    if request.method == 'POST':
        form = RequirementForm(request.POST)
        if form.is_valid():
            req_text = form.cleaned_data['req']
            if req_text is None or req_text == "":
                return render(request, 'UI/index.html', {
                    "error": "متنی وارد نکرده‌اید."
                })

            requirement = Requirement(req_text, hazm_extractor.extract)
            extractor = ClassDiagramExtractor(requirement)
            extractor.extract_diagram()
            request.session['result'] = {
                'classes': [{'text': element.text, 'attributes': [attr.text for attr in element.attributes],
                             'operations': [operation.text for operation in element.operations]} for element in
                            extractor.diagram.classes],
                'relations': [
                    {'source': relation.source.text, 'relation_type': relation.relation_type,
                     'target': relation.target.text,
                     'label': relation.label} for relation in extractor.diagram.relations]
            }
            request.session['mermaid'] = extractor.diagram.to_mermaid()
            request.session['req'] = requirement.serialize()
            return HttpResponseRedirect(reverse('UI:diagram'))
        else:
            req_text = form.data['req']
    else:
        req_text = ''
        old_req = request.session.get('req')
        if old_req is not None:
            req_text = old_req['text']
        form = RequirementForm(initial={'req': req_text})
    return render(request, 'UI/index.html', {'req': req_text, 'form': form})


def submit_req(request):
    if request.method == 'POST':
        form = RequirementForm(request.POST)
        if form.is_valid():
            req_text = form.cleaned_data['req']
            if req_text is None or req_text == "":
                return render(request, 'UI/index.html', {
                    "error": "متنی وارد نکرده‌اید."
                })

            requirement = Requirement(req_text, hazm_extractor.extract)
            extractor = ClassDiagramExtractor(requirement)
            extractor.extract_diagram()
            request.session['result'] = {
                'classes': [{'text': element.text, 'attributes': [attr.text for attr in element.attributes],
                             'operations': [operation.text for operation in element.operations]} for element in
                            extractor.diagram.classes],
                'relations': [
                    {'source': relation.source.text, 'relation_type': relation.relation_type,
                     'target': relation.target.text,
                     'label': relation.label} for relation in extractor.diagram.relations]
            }
            request.session['mermaid'] = extractor.diagram.to_mermaid()
            request.session['req'] = requirement.serialize()
            return HttpResponseRedirect(reverse('UI:diagram'))


def diagram(request):
    result = request.session.get('result')
    requirement = request.session.get('req')
    result_json = json.dumps(result, ensure_ascii=False)
    requirement_json = json.dumps(requirement, ensure_ascii=False)
    warning_nodes_addresses = []
    for sentence in requirement['sentences']:
        for node in sentence['nlp_nodes']:
            if (node['tag'] == 'VERB' and 'شد' in node['lemma']) or node['tag'] == 'PRON':
                warning_nodes_addresses.append([sentence['index'], node['address']])
    return render(request, 'UI/diagram.html',
                  {'result': result_json, 'req': requirement_json, 'req_text': requirement['text'],
                   'warning_nodes': warning_nodes_addresses, 'mermaid': request.session.get('mermaid')})


def about(request):
    return render(request, 'UI/about.html')


def contact(request):
    return render(request, 'UI/contact.html')


def samples(request):
    id = int(request.GET.get('id', '0'))
    print('ffffffffffff')
    print(id)

    samples = [
        {
            'id': 0,
            'title': 'فروشگاه آنلاین',
            'text': (
                "سیستم خرید آنلاین به مشتری‌ها این امکان را می‌دهد که محصول‌ها را بر اساس دسته‌بندی جستجو کرده و "
                "آن‌ها را سفارش دهند. هر دسته‌بندی شامل دسته‌بندی یا محصول‌ها است. مشتری‌ها می‌توانند محصول‌هایی "
                "را که با معیارهای جستجوی آن‌ها مطابقت دارد، جستجو کنند. یک ادمین دسته‌بندی‌ها و اطلاعات محصول "
                "را مدیریت می‌کند. مشتری‌ها می‌توانند حساب کاربری ایجاد کنند. یک حساب کاربری شامل اطلاعاتی مانند "
                "نام، آدرس، شماره تلفن،آدرس ایمیل خواهد بود.\n\n"
                "مشتری‌ها می‌توانند یک یا چند محصول را به سبد خرید خود اضافه کنند. سبد خرید فهرستی از محصول‌ها را "
                "نمایش می‌دهد و قیمت آن‌ها را نشان می‌دهد. سبد خرید قیمت کل اقلام موجود در سبد خرید را نیز نشان "
                "می‌دهد. مشتری‌ها می‌توانند قبل از پرداخت، محصول‌ها را از سبد خرید حذف کنند.\n\n"
                "فرآیند پرداخت زمانی آغاز می‌شود که مشتری‌ها سفارش خود را تأیید کنند. مشتری‌ها پرداخت خواهند کرد "
                "و یک ایمیل تأیید دریافت خواهند کرد. ایمیل تأیید، سفارش را نشان می‌دهد. اطلاعات سفارش شامل "
                "مشتری، محصول‌ها، قیمت‌ها، مقادیر، آدرس تحویل و تاریخ تحویل است."
            ),
            'src': 'online shopping.svg'
        },
        {
            'id': 1,
            'title': 'گروه موسیقی',
            'text': "یک گروه موسیقی بیش از یک نوازنده دارد.یک نوازنده جدید می تواند به گروه موسیقی ملحق شود یا هر "
                    "نوازنده ای می تواند گروه موسیقی را ترک کند. نوازنده دارای اطلاعات نام، سن، جنسیت، نام گروه  "
                    "موسیقی و ساز است. نوازنده‌ها با نواختن ساز به اجرای نمایش می پردازند. سازها در 3 گروه گیتار، "
                    "درام و کیبورد دسته بندی می شوند. نوازنده‌ها نوازنده گیتار،نوازنده کیبورد و نوازنده درام هستند. "
                    "نوازنده گیتار گیتار می نوازد. نوازنده درام درام می‌نوازد. نوازنده کیبورد کیبورد می‌نوازد.  هنگام "
                    "نواختن سازها سیستم باید نام ساز و نوازنده را نشان دهد.",
            'src': 'Music band.svg'
        }
    ]

    if id > len(samples) - 1:
        id = 0
    return render(request, 'UI/samples.html', samples[id])

PR2CD_UI/UI/templates/UI/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="about-container">
    <div>
        <p>
            این سامانه مربوط به پایان نامه با عنوان «استخراج خودکار نمودار کلاس از متن نیازمندی‌ها در زبان فارسی» است.

        </p>
        <p>
            پایان‌نامه توسط «علی قیومی» و راهنمایی استاد «دکتر محمد‌هادی علائیان» انجام گرفته است.
        </p>
        <p>
            مجموعه‌داده و کدها از طریق
            <a class="color-link" href="https://github.com/aliqb/PR2CD" target="_blank">گیتهاب</a>
            در دسترس است.
        </p>
        <p>
            لطفاً به منظور اعمال نظر یا ارسال اشتباهات صورت گرفته توسط سامانه و ارسال فیدبک به آدرس زیر پیام ارسال کنید.
        </p>
        <a class="english">kntupr2cd@gmail.com</a>
    </div>
    <div class="thesis">
        <p class="abstract">
            مهندسی نیازمندی‌های نرم‌افزار و تحلیل نیازمندی‌ها نخستین مرحله در توسعه یک نرم‌افزار است و تأثیر زیادی در
            مراحل بعدی و نتیجه‌ی نهایی دارد. از جمله کارهایی که در مهندسی نیازمندی‌ها انجام می‌گیرد مدل‌سازی نیازمندی به
            شکل نمودارهای مختلف است. نیازمندی‌ها به زبان طبیعی نوشته می‌شوند و این باعث می‌شود فرایند تبدیل آن‌ها به
            نمودار سخت و زمان‌بر باشد؛مهندسی نیازمندی‌های نرم‌افزار و تحلیل نیازمندی‌ها نخستین مرحله در توسعه یک
            نرم‌افزار است و تأثیر زیادی در مراحل بعدی و نتیجه‌ی نهایی دارد. از جمله کارهایی که در مهندسی نیازمندی‌ها
            انجام می‌گیرد مدل‌سازی نیازمندی به شکل نمودارهای مختلف است. نیازمندی‌ها به زبان طبیعی نوشته می‌شوند و این
            باعث می‌شود فرایند تبدیل آن‌ها به نمودار سخت و زمان‌بر باشد؛ پژوهش‌هایی برای خودکار کردن این روند انجام
            گرفته است که اکثرا مربوط به زبان انگلیسی هستند. این پروژه به همین دلایل برای استخراج خودکار
            نمودار کلاس از متن نیازمندی فارسی توسعه یافته است. متن نیازمندی به زبان فارسی از کاربر دریافت می‌شود؛ ابتدا
            بر روی این متن با پردازش زبان طبیعی
            اطلاعات زبانی و ساختاری استخراج می‌شود؛ سپس برای هر یک از عناصر نمودار دسته‌ای از قوانین وجود دارد که متن و
            اطلاعات مرحله قبل در برابر این قوانین بررسی می‌گردند و اجزای نمودار استخراج می‌گردد. در نهایت نمودار به فرمت
            mermaid تبدیل شده و نمایش داده می‌شود.
        </p>
        <a class="thesis-link" href="{% static 'thesis.pdf' %}" target="_blank">قسمتی از پایان‌نامه</a>
    </div>

</div>
{% endblock %}

PR2CD_UI/UI/templates/UI/contact.html
{% extends "base.html" %}

{% block content %}
<div class="about-container">
    <p>
        لطفاً به منظور اعمال نظر یا ارسال اشتباهات صورت گرفته توسط سامانه و ارسال فیدبک به آدرس زیر پیام ارسال کنید.
    </p>
    <a class="english">kntupr2cd@gmail.com</a>
</div>
{% endblock %}

PR2CD_UI/UI/templates/UI/diagram.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div>
    <div class="main-container">
        <div class="diagram-container">
            <div id="diagram-div">
            </div>
            <img class="watermark" src="{% static 'images/kntu-logo-title.png' %}"/>

            <button id="svg-btn" class="btn">ذخیره</button>

        </div>
        <div class="sentences-container">
            <div class="sentences-main-mode">
                <div class="d-flex sentences-btn-container">
                    <button class="btn outline edit-req-btn">ویرایش</button>
                    {% if warning_nodes|length > 0 %}
                    <p class="warning-hint">تغییر موارد هایلایت زرد شده می‌تواند در بهبود عملکرد مؤثر باشد.</p>
                    {% endif %}
                </div>

            </div>
            <div class="sentences-edit-mode d-none">

                <form action="{% url 'UI:submit' %}" method="post">
                    {% csrf_token %}

                    <div class="d-flex sentences-btn-container sentences-edit-node">
                        <button href="{% url 'UI:index' %}" class="btn outline cancel-req-btn" type="button">انصراف
                        </button>
                        <button href="{% url 'UI:index' %}" class="btn">ذخیره</button>
                    </div>
                    <textarea name="req" class="sentence-textarea" rows="20">{{ req_text }}</textarea>
                </form>

            </div>
            <div class="return-container">
                <a href="{% url 'UI:index' %}" class="btn outline">بازگشت</a>
            </div>
        </div>
    </div>


    <!--    <button id="export-btn">test</button>-->
    <!--    <button id="svg-btn">test-svg</button>-->

</div>
<script>
    mermaid.initialize({startOnLoad: true, securityLevel: 'loose'});
    const svgButton = document.getElementById("svg-btn")
    const sentencesMainContainer = document.querySelector('.sentences-main-mode')
    const sentencesEditContainer = document.querySelector('.sentences-edit-mode')
    const editSentencesBtn = document.querySelector('.edit-req-btn')
    const cancelSentencesBtn = document.querySelector('.cancel-req-btn')
    const warning_nodes = JSON.parse('{{ warning_nodes|safe|escapejs }}')
    drawDiagram()
    write_requirement()


    editSentencesBtn.addEventListener('click', onEdit)
    cancelSentencesBtn.addEventListener('click', onCancelEdit)
    svgButton.addEventListener('click', exportSvg)

    async function drawDiagram() {
        const umlData = JSON.parse('{{ result|safe|escapejs }}');
        const element = document.querySelector('#diagram-div');
        if (!umlData.classes.length) {
            element.innerHTML = '<p class="no-class-text">متأسفانه کلاسی شناسایی نشد.</p>';
            svgButton.disabled = true;
            return
        }
        svgButton.disabled = false
        let diagramDef = '{{ mermaid|safe|escapejs }}';
        const {svg, bindFunctions} = await mermaid.render('graphDiv', diagramDef);
        element.innerHTML = svg;
        // This can also be written as `bindFunctions?.(element);` using the `?` shorthand.
        if (bindFunctions) {
            bindFunctions(element);
        }
    }

    function test(item) {
        console.log('test', item)
    }

    function write_requirement() {
        const requirement = JSON.parse('{{ req|safe|escapejs }}');
        const p = document.createElement('p')
        p.classList.add('sentences-p')
        requirement.sentences.forEach(sentence => {
            const sentenceElement = get_sentence_element(sentence)
            // sentenceElement.innerText += '. '
            p.appendChild(sentenceElement)
        })
        sentencesMainContainer.appendChild(p)
    }

    function get_sentence_element(sentence) {
        const sentenceContainer = document.createElement('span')
        sentenceContainer.classList.add('sentence')
        sentenceContainer.classList.add(`s-${sentence.index}`)
        // sentence_container.innerText = `${sentence.text}. `
        sentence.nlp_nodes.forEach((node, index) => {
            const nodeContainer = document.createElement('span')
            nodeContainer.classList.add('node')
            nodeContainer.classList.add(`n-${node.address}`)

            nodeContainer.innerText = index == 0 || node.tag == 'PUNCT' ? node.text : ` ${node.text}`
            if (index == sentence.nlp_nodes.length - 1) {
                nodeContainer.innerText += '.'
            }
            if (node.tag === 'VERB') {
                nodeContainer.innerText = nodeContainer.innerText.replace('_', '‌')
            }
            if (node_has_warning(sentence.index, node.address)) {
                nodeContainer.classList.add('node-warning')
            }
            sentenceContainer.appendChild(nodeContainer)
        })
        return sentenceContainer
    }


    function onEdit() {
        sentencesMainContainer.classList.add('d-none')
        sentencesEditContainer.classList.remove('d-none')
    }

    function onCancelEdit() {
        sentencesMainContainer.classList.remove('d-none')
        sentencesEditContainer.classList.add('d-none')
    }

    function node_has_warning(sentence_index, node_address) {
        return warning_nodes.some(pair => pair[0] === sentence_index && pair[1] === node_address)
    }

    function exportSvg() {
        // Select the rendered SVG element
        const svgElement = document.querySelector("svg");

        // Clone the SVG element to modify without affecting the original
        const svgClone = svgElement.cloneNode(true);

        // Temporarily append the cloned SVG to the document to allow it to calculate its dimensions
        const tempContainer = document.createElement('div');
        tempContainer.style.position = 'absolute';
        tempContainer.style.visibility = 'hidden';
        document.body.appendChild(tempContainer);
        tempContainer.appendChild(svgClone);

        // Create a style element with embedded styles
        const styleElement = document.createElement("style");
        styleElement.textContent = `
        svg {
            font-family: none !important;
        }
    `;
        svgClone.insertBefore(styleElement, svgClone.firstChild);

        // Get the logo image as base64 data URL
        const logoUrl = "{% static 'images/kntu-logo-title.png' %}"; // Adjust this path if needed
        const logoImg = new Image();
        logoImg.src = logoUrl;

        logoImg.onload = () => {
            // Convert the image to base64
            const canvas = document.createElement("canvas");
            const ctx = canvas.getContext("2d");
            canvas.width = logoImg.width;
            canvas.height = logoImg.height;
            ctx.drawImage(logoImg, 0, 0);

            const base64Logo = canvas.toDataURL("image/png");

            // Get the SVG height to position the image at the bottom
            const svgHeight = svgClone.getBBox().height;
            // Create an image element to add to the SVG
            const imgElement = document.createElementNS("http://www.w3.org/2000/svg", "image");

            imgElement.setAttribute("x", "10"); // Position at the left
            imgElement.setAttribute("y", svgClone.getBBox().height); // Position at the bottom
            imgElement.setAttribute("width", "50"); // Adjust the width as needed
            // imgElement.setAttribute("height", "100"); // Adjust the height as needed
            imgElement.setAttribute("href", base64Logo);

            // Add the image element to the cloned SVG
            svgClone.appendChild(imgElement);

            // Serialize the modified SVG
            const svgData = new XMLSerializer().serializeToString(svgClone);

            // Create a Blob and URL for the modified SVG data
            const blob = new Blob([svgData], {type: "image/svg+xml;charset=utf-8"});
            const url = URL.createObjectURL(blob);

            // Create a link to download the SVG file
            const link = document.createElement("a");
            link.href = url;
            link.download = "diagram_with_logo.svg";
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
            document.body.removeChild(tempContainer)
        };
    }

</script>
{% endblock %}

PR2CD_UI/UI/templates/UI/index.html
{% extends "base.html" %}
{% block content %}
<div class=" d-flex form-container">
    <form action="{% url 'UI:index' %}" method="post" class="m-auto d-flex flex-col centering" novalidate>
        {% csrf_token %}

        <div class="d-flex flex-col">
            <label for="{{ form.req.id_for_label }}" class="main-prompt">متن نیازمندی را وارد کنید</label>


            <div>
                <label for="requirement-file" class="btn outline file-label">بارگذاری فایل</label>
                <input id="requirement-file" type="file" class="d-none"
                       accept=".txt, .pdf, .doc, .docx, text/plain, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document">
            </div>
             {% if form.req.errors %}
            <div class="error">{{ form.req.errors|join:", " }}</div>
            {% endif %}
            {{ form.req }}
            <div class="recaptcha-container">
                {{ form.captcha }}
                {% if form.captcha.errors %}
                <div class="error">خطا در تأیید ریکپتچا، لطفا مجدد تلاش کنید.</div>
                {% endif %}
            </div>
        </div>
        <div class="send-container">
            <input type="submit" value="ارسال" class="btn">
        </div>
    </form>
</div>
<script>
    const inputFile = document.querySelector("#requirement-file")
    const textArea = document.querySelector("#req")

    function onInputFile(event) {
        const file = event.target.files[0]; // Get the first selected file
        const reader = new FileReader();
        if (file) {
            if (file.type === "text/plain") {
                readTextFile(file, reader)
            } else if (file.type === "application/pdf") {
                readPdf(file, reader)
            } else if (
                file.type === "application/msword" ||
                file.type === "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            ) {
                readDocx(file, reader)
            } else {
                textArea.value = 'فرمت فایل صحیح نیست.'
            }
        }
    }

    function readTextFile(file, reader) {
        reader.onload = function (e) {
            textArea.value = e.target.result; // Populate the textarea with the file content
        }
        reader.readAsText(file, "UTF-8"); // Read the file as text
    }

    function readPdf(file, reader) {
        reader.onload = function (e) {
            const pdfData = new Uint8Array(e.target.result);
            // Load the PDF using PDF.js
            pdfjsLib.getDocument({data: pdfData}).promise.then(pdf => {
                let textContent = '';
                const maxPages = pdf.numPages;

                // Extract text from each page
                let pagePromises = [];
                for (let pageNum = 1; pageNum <= maxPages; pageNum++) {
                    pagePromises.push(
                        pdf.getPage(pageNum).then(page => {
                            return page.getTextContent().then(text => {
                                text.items.forEach(item => {
                                    textContent += item.str + " ";
                                });
                            });
                        })
                    );
                }

                // Once all pages are processed
                Promise.all(pagePromises).then(() => {
                    textArea.value = textContent;
                });
            });
        };
        reader.readAsArrayBuffer(file);
    }

    function readDocx(file, reader) {
        reader.onload = function (e) {
            // Use Mammoth.js to extract text from Word documents
            mammoth.extractRawText({arrayBuffer: e.target.result})
                .then(result => {
                    textArea.value = result.value; // The extracted text
                })
                .catch(error => {
                    textArea.value = "Error parsing Word document.";
                });
        };
        reader.readAsArrayBuffer(file);
    }

    inputFile.addEventListener('input', onInputFile)
</script>
{% endblock %}

PR2CD_UI/UI/templates/UI/samples.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div>
    <div class="samples-container">
        <div class="sample-text">
            <h2>نیازمندی {{title}}</h2>
            <p>
                {{ text }}
            </p>
<!--            because its only 2 sample-->
            <div class="slider">
                <a  id="slide1" class="slide-number {% if id == 0 %}active{% endif %}" href="{% url 'UI:samples' %}?id=0">1</a>
                <a id="slide2" class="slide-number {% if id == 1 %}active{% endif %}" href="{% url 'UI:samples' %}?id=1">2</a>

            </div>
        </div>
        <div class="diagram-container">
            <div id="diagram-div">
                <img src="{% static 'images/samples/' %}{{src}}">
            </div>
            <img class="watermark" src="{% static 'images/kntu-logo-title.png' %}"/>

        </div>

    </div>

</div>
{% endblock %}